"""Marker Making Sec 1.8 (splice marks / fabric-roll handling): add markers.splice_min_length /
splice_max_length / splice_margin / splice_separation and dmp.splice_marks.

The four new marker columns are "Settings/Splice" [GMM] -- a single per-marker settings group
(minimum/maximum mark length, margin, separation from the marker edge), not a named/reusable
table like matching_rule_tables or block_buffer_rule_tables (the plan doc never calls it
"Splice Rule Table" the way it does for those two), so they live directly on `markers` alongside
the other already-marker-scoped settings (fabric_width, ply_count, ...).

`dmp.splice_marks` is a fresh table, same audited/versioned/soft-deleted shape as `fuse_blocks`:
one row per mark, `start_x`/`end_x` spanning the overlap zone along the marker's length axis
(X, same convention as marker_length/bite-boundary elsewhere in this app), `source` distinguishing
`'auto'` (regenerated by marker-making-service's splice/auto endpoint) from `'manual'` (added by
hand and never touched by a regenerate -- "manual entries take priority over auto-generated ones"
[GMM]), and an optional `roll_id` -- the field the plan's Sec 1.13 bundle-tag manifest's
`lot/roll_id` is meant to be sourced from, carried here as plain opaque text since there's no
fabric-roll entity anywhere in this platform to foreign-key against.

Revision ID: 0012
Revises: 0011
Create Date: 2026-09-07
"""

from alembic import op

revision = "0012"
down_revision = "0011"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        ALTER TABLE dmp.markers
            ADD COLUMN splice_min_length numeric(8,3) NULL,
            ADD COLUMN splice_max_length numeric(8,3) NULL,
            ADD COLUMN splice_margin numeric(8,3) NULL,
            ADD COLUMN splice_separation numeric(8,3) NULL;

        CREATE TABLE dmp.splice_marks (
            id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
            organization_id     uuid NOT NULL REFERENCES dmp.organizations(id),
            marker_id           uuid NOT NULL REFERENCES dmp.markers(id),
            start_x             numeric(10,3) NOT NULL,
            end_x               numeric(10,3) NOT NULL,
            source              text NOT NULL CHECK (source IN ('auto','manual')),
            roll_id             text NULL,
            created_by          uuid NOT NULL REFERENCES dmp.users(id),
            created_at          timestamptz NOT NULL DEFAULT now(),
            updated_by          uuid NOT NULL REFERENCES dmp.users(id),
            updated_at          timestamptz NOT NULL DEFAULT now(),
            deleted_at          timestamptz NULL,
            version             integer NOT NULL DEFAULT 1,
            CHECK (end_x > start_x)
        );
        CREATE INDEX idx_splice_marks_marker ON dmp.splice_marks(marker_id);
        """
    )

    # -- Permissions (ids continue from 0009's 56-61, so next free id is 62) --------------------
    op.execute(
        """
        INSERT INTO dmp.permissions (id, code, resource, action, description) VALUES
            (62, 'splice_mark.read',   'splice_mark', 'read',   'Read a splice_mark.'),
            (63, 'splice_mark.write',  'splice_mark', 'write',  'Write a splice_mark.'),
            (64, 'splice_mark.delete', 'splice_mark', 'delete', 'Delete a splice_mark.');

        INSERT INTO dmp.role_permissions (role_id, permission_id)
        SELECT r.id, p.id FROM dmp.roles r, dmp.permissions p
        WHERE r.code = 'admin' AND p.code IN ('splice_mark.read', 'splice_mark.write', 'splice_mark.delete');

        INSERT INTO dmp.role_permissions (role_id, permission_id)
        SELECT r.id, p.id FROM dmp.roles r, dmp.permissions p
        WHERE r.code = 'marker_maker' AND p.code IN ('splice_mark.read', 'splice_mark.write', 'splice_mark.delete');

        INSERT INTO dmp.role_permissions (role_id, permission_id)
        SELECT r.id, p.id FROM dmp.roles r, dmp.permissions p
        WHERE r.code IN ('pattern_maker', 'production_planner', 'viewer', 'auditor', 'contractor_qa')
          AND p.code = 'splice_mark.read';
        """
    )


def downgrade() -> None:
    op.execute(
        """
        DELETE FROM dmp.role_permissions WHERE permission_id BETWEEN 62 AND 64;
        DELETE FROM dmp.permissions WHERE id BETWEEN 62 AND 64;
        DROP TABLE dmp.splice_marks;
        ALTER TABLE dmp.markers
            DROP COLUMN splice_separation,
            DROP COLUMN splice_margin,
            DROP COLUMN splice_max_length,
            DROP COLUMN splice_min_length;
        """
    )
